// AUTO-GENERATED by build.rs — DO NOT EDIT MANUALLY
// Source of truth: src/chunk.rs, src/constants.rs, src/render_mode.rs, src/svt.rs

// Block types (generated from src/chunk.rs BlockType enum)
#define BLOCK_AIR 0u
#define BLOCK_STONE 1u
#define BLOCK_DIRT 2u
#define BLOCK_GRASS 3u
#define BLOCK_PLANKS 4u
#define BLOCK_LEAVES 5u
#define BLOCK_SAND 6u
#define BLOCK_GRAVEL 7u
#define BLOCK_WATER 8u
#define BLOCK_GLASS 9u
#define BLOCK_LOG 10u
#define BLOCK_MODEL 11u
#define BLOCK_BRICK 12u
#define BLOCK_SNOW 13u
#define BLOCK_COBBLESTONE 14u
#define BLOCK_IRON 15u
#define BLOCK_BEDROCK 16u
#define BLOCK_TINTED_GLASS 17u
#define BLOCK_PAINTED 18u
#define BLOCK_LAVA 19u
#define BLOCK_GLOW_STONE 20u
#define BLOCK_GLOW_MUSHROOM 21u
#define BLOCK_CRYSTAL 22u
#define BLOCK_PINE_LOG 23u
#define BLOCK_WILLOW_LOG 24u
#define BLOCK_PINE_LEAVES 25u
#define BLOCK_WILLOW_LEAVES 26u
#define BLOCK_ICE 27u
#define BLOCK_MUD 28u
#define BLOCK_SANDSTONE 29u
#define BLOCK_CACTUS 30u
#define BLOCK_DECORATIVE_STONE 31u
#define BLOCK_CONCRETE 32u
#define BLOCK_DEEPSLATE 33u
#define BLOCK_MOSS 34u
#define BLOCK_MOSSY_COBBLESTONE 35u
#define BLOCK_CLAY 36u
#define BLOCK_DRIPSTONE 37u
#define BLOCK_CALCITE 38u
#define BLOCK_TERRACOTTA 39u
#define BLOCK_PACKED_ICE 40u
#define BLOCK_PODZOL 41u
#define BLOCK_MYCELIUM 42u
#define BLOCK_COARSE_DIRT 43u
#define BLOCK_ROOTED_DIRT 44u
#define BLOCK_BIRCH_LOG 45u
#define BLOCK_BIRCH_LEAVES 46u

// Texture atlas tile count (generated from src/constants.rs)
const float ATLAS_TILE_COUNT = 45.0;
const float ATLAS_TILE_SIZE = 1.0 / ATLAS_TILE_COUNT;

// World/chunk dimensions (generated from src/chunk.rs + src/constants.rs + src/svt.rs)
const uint CHUNK_SIZE = 32u;
const uint CHUNKS_X = 16u;
const uint CHUNKS_Y = 16u;
const uint CHUNKS_Z = 16u;
const uint BRICK_SIZE = 8u;
const uint BRICKS_PER_AXIS = 4u;
const uint BRICKS_PER_CHUNK = 64u;

// Tint palette (generated from src/chunk.rs TINT_PALETTE)
const vec3 TINT_PALETTE[32] = vec3[32](
    vec3(1.0000, 0.2000, 0.2000),
    vec3(1.0000, 0.5000, 0.2000),
    vec3(1.0000, 1.0000, 0.2000),
    vec3(0.5000, 1.0000, 0.2000),
    vec3(0.2000, 1.0000, 0.2000),
    vec3(0.2000, 1.0000, 0.5000),
    vec3(0.2000, 1.0000, 1.0000),
    vec3(0.2000, 0.5000, 1.0000),
    vec3(0.2000, 0.2000, 1.0000),
    vec3(0.5000, 0.2000, 1.0000),
    vec3(1.0000, 0.2000, 1.0000),
    vec3(1.0000, 0.2000, 0.5000),
    vec3(0.9500, 0.9500, 0.9500),
    vec3(0.6000, 0.6000, 0.6000),
    vec3(0.3000, 0.3000, 0.3000),
    vec3(0.4000, 0.2500, 0.1000),
    vec3(0.8000, 0.4000, 0.4000),
    vec3(0.8000, 0.6000, 0.4000),
    vec3(0.8000, 0.8000, 0.4000),
    vec3(0.6000, 0.8000, 0.4000),
    vec3(0.4000, 0.8000, 0.4000),
    vec3(0.4000, 0.8000, 0.6000),
    vec3(0.4000, 0.8000, 0.8000),
    vec3(0.4000, 0.6000, 0.8000),
    vec3(0.4000, 0.4000, 0.8000),
    vec3(0.6000, 0.4000, 0.8000),
    vec3(0.8000, 0.4000, 0.8000),
    vec3(0.8000, 0.4000, 0.6000),
    vec3(0.2000, 0.1500, 0.1000),
    vec3(0.1000, 0.2000, 0.1000),
    vec3(0.1000, 0.1000, 0.2000),
    vec3(0.2000, 0.1000, 0.2000)
);

// Render modes (generated from src/render_mode.rs RenderMode enum)
#define RENDER_MODE_COORD 0u
#define RENDER_MODE_STEPS 1u
#define RENDER_MODE_TEXTURED 2u
#define RENDER_MODE_NORMAL 3u
#define RENDER_MODE_UV 4u
#define RENDER_MODE_DEPTH 5u
#define RENDER_MODE_BRICK_DEBUG 6u
#define RENDER_MODE_SHADOW_DEBUG 7u

